---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge 


### content configuration ###
title: Bioinformatics Consulting for HMS
keywords: bioinformatics, hms, tnt, consult
description: Support in high-dimensional data management, analysis and dissemination for Harvard Medical School through the HSPH Bioinformatics Core
#source_link:
#favicon:
#touch_icon:
#google_analytics_key:


### template colors, used site-wide via css ###
colors:
  black:
    light: '#303030'
    dark: '#111111'
  white:
    light: '#f5f5f5'
    dark: '#f8f8f8'
  blue:
    light: '#3c9eec'
    dark: '#49a7e9'
  green:
    light: '#a3d832'
    dark: '#9bcf2f'
  purple:
    light: '#c869bf'
    dark: '#c869bf'
  orange:
    light: '#faaf22'
    dark: '#fab125'
  turquoise:
    light: '#0fbfcf'
    dark: '#0fbfcf'
  color1:
    light: '#E3E1D3'
    dark: '#DCBB7D'
  color2:
    light: '#B65558'
    dark: '#8F4244'
  color3:
    light: '#828BA1'
    dark: '#595F6D'
  color4:
    light: '#C8BFCA'
    dark: '#9A8A98'
  color5:
    light: '#A1A1A1'
    dark: '#757575'
